-- Run this in the Supabase SQL Editor to initialize the database.
-- 0. Extensions
create extension if not exists postgis;
create extension if not exists "uuid-ossp";

-- 1. Profiles (Extends Supabase Auth)
create table profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  role text check (role in ('admin', 'employee')) default 'employee',
  base_location geography(POINT), -- Office/Home location
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Work Plans (Daily)
create table work_plans (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id) not null,
  date date not null,
  tasks text[], -- Array of task descriptions/destinations
  planned_route geography(LINESTRING), -- Expected path
  status text check (status in ('pending', 'approved', 'rejected')) default 'pending',
  submitted_at timestamp with time zone default now()
);

-- 3. GPS Logs (High Frequency)
create table gps_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  location geography(POINT) not null,
  heading float,
  speed float,
  accuracy float,
  battery_level float,
  is_mocked boolean default false,
  timestamp timestamp with time zone default now()
);

-- 4. Expenses
create table expenses (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id) not null,
  amount numeric(10, 2) not null,
  category text,
  description text,
  receipt_url text, -- Supabase Storage URL
  location_tagged geography(POINT), -- Where expense was incurred
  status text check (status in ('pending', 'approved', 'rejected', 'paid')) default 'pending',
  created_at timestamp with time zone default now()
);

-- 5. Deviations (Alerts)
create table deviations (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references profiles(id) not null,
  deviation_point geography(POINT),
  distance_from_route float, -- in meters
  reason text,
  severity text check (severity in ('low', 'medium', 'high')),
  created_at timestamp with time zone default now()
);

-- RLS Policies (Row Level Security) - Basic Setup
alter table profiles enable row level security;
alter table work_plans enable row level security;
alter table gps_logs enable row level security;
alter table expenses enable row level security;
alter table deviations enable row level security;

-- Policies (Simplified for MVP)
-- Public read for ease (lock down in production)
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profiles." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- Logs: Admin reads all, User inserts own
create policy "Admins read all logs" on gps_logs for select using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
create policy "Users insert own logs" on gps_logs for insert with check (auth.uid() = user_id);

-- 6. Trigger for profile creation on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'full_name', 'employee');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

