-- ============================================================
-- ARSPL SALES TRACKER - COMPLETE SCHEMA FOR NEW SUPABASE PROJECT
-- Run this entire file in: Supabase SQL Editor → New Query → Run
-- ============================================================

-- 0. Extensions
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- TABLES
-- ============================================================

-- 1. Profiles
CREATE TABLE IF NOT EXISTS profiles (
  id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name text,
  role text CHECK (role IN ('admin', 'employee')) DEFAULT 'employee',
  base_location geography(POINT),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 2. GPS Logs
CREATE TABLE IF NOT EXISTS gps_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES profiles(id) NOT NULL,
  location geography(POINT) NOT NULL,
  heading float,
  speed float,
  accuracy float,
  battery_level float,
  is_mocked boolean DEFAULT false,
  distance_from_last_point float,
  timestamp timestamp with time zone DEFAULT now()
);

-- 3. Areas / Zones
CREATE TABLE IF NOT EXISTS areas (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  name text NOT NULL,
  boundary geography(POLYGON),
  assigned_staff_id uuid REFERENCES profiles(id),
  created_at timestamp with time zone DEFAULT now()
);

-- 4. Leads (CRM)
CREATE TABLE IF NOT EXISTS leads (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  name text NOT NULL,
  area_id uuid REFERENCES areas(id),
  created_by_id uuid REFERENCES profiles(id) NOT NULL,
  assigned_staff_id uuid REFERENCES profiles(id),
  status text DEFAULT 'new',
  last_visit_date timestamp with time zone,
  priority_score int DEFAULT 1,
  metadata jsonb,
  mobile text,
  address text,
  business_id text,
  created_at timestamp with time zone DEFAULT now()
);

-- 5. Attendance
CREATE TABLE IF NOT EXISTS attendance (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES profiles(id) NOT NULL,
  check_in timestamp with time zone NOT NULL,
  check_out timestamp with time zone,
  status text CHECK (status IN ('active', 'completed')),
  selfie_url text,
  total_distance float DEFAULT 0,
  created_at timestamp with time zone DEFAULT now()
);

-- 6. Expenses
CREATE TABLE IF NOT EXISTS expenses (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES profiles(id) NOT NULL,
  amount numeric(10, 2) NOT NULL,
  category text,
  description text,
  receipt_url text,
  location_tagged geography(POINT),
  status text CHECK (status IN ('pending', 'approved', 'rejected', 'paid')) DEFAULT 'pending',
  expense_type text CHECK (expense_type IN ('travel', 'food', 'hotel', 'fuel', 'other')) DEFAULT 'other',
  expense_date date DEFAULT CURRENT_DATE,
  bill_url text,
  linked_travel_date date,
  is_auto_generated boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

-- 7. Deviations
CREATE TABLE IF NOT EXISTS deviations (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id uuid REFERENCES profiles(id) NOT NULL,
  deviation_point geography(POINT),
  distance_from_route float,
  reason text,
  severity text CHECK (severity IN ('low', 'medium', 'high')),
  created_at timestamp with time zone DEFAULT now()
);

-- 8. Daily Work Plans
CREATE TABLE IF NOT EXISTS daily_work_plans (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  staff_id uuid REFERENCES profiles(id) NOT NULL,
  date date NOT NULL,
  planned_leads jsonb,
  planned_route geography(LINESTRING),
  expected_start_time time,
  expected_end_time time,
  status text CHECK (status IN ('draft', 'active', 'completed')) DEFAULT 'draft',
  created_at timestamp with time zone DEFAULT now(),
  activated_at timestamp with time zone,
  completed_at timestamp with time zone,
  UNIQUE(staff_id, date)
);

-- 9. Daily Travel Summary
CREATE TABLE IF NOT EXISTS daily_travel_summary (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  staff_id uuid REFERENCES profiles(id) NOT NULL,
  date date NOT NULL,
  total_km numeric(10, 2) NOT NULL DEFAULT 0,
  travel_amount numeric(10, 2) NOT NULL DEFAULT 0,
  gps_log_count int DEFAULT 0,
  status text CHECK (status IN ('pending', 'approved', 'rejected')) DEFAULT 'pending',
  created_at timestamp with time zone DEFAULT now(),
  approved_at timestamp with time zone,
  approved_by uuid REFERENCES profiles(id),
  UNIQUE(staff_id, date)
);

-- 10. Visit Reports
CREATE TABLE IF NOT EXISTS visit_reports (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  lead_id uuid REFERENCES leads(id),
  staff_id uuid REFERENCES profiles(id) NOT NULL,
  meeting_id text,
  client_name text,
  lead_type text CHECK (lead_type IN ('new', 'follow-up', 'conversion', 'support')),
  discussion_summary text,
  outcome text,
  order_value numeric(12, 2) DEFAULT 0,
  expected_order_date date,
  next_action_date date,
  status text DEFAULT 'Completed',
  photo_url text,
  location geography(POINT),
  timestamp timestamp with time zone DEFAULT now()
);

-- 11. Audit Logs
CREATE TABLE IF NOT EXISTS audit_logs (
  id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  action text NOT NULL,
  performed_by uuid REFERENCES profiles(id),
  old_data jsonb,
  new_data jsonb,
  timestamp timestamp with time zone DEFAULT now()
);

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_daily_work_plans_staff_date ON daily_work_plans(staff_id, date);
CREATE INDEX IF NOT EXISTS idx_daily_work_plans_status ON daily_work_plans(status);
CREATE INDEX IF NOT EXISTS idx_daily_travel_summary_staff_date ON daily_travel_summary(staff_id, date);

-- ============================================================
-- RLS (Row Level Security)
-- ============================================================
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE visit_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE gps_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_work_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_travel_summary ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE deviations ENABLE ROW LEVEL SECURITY;

-- Profiles
CREATE POLICY "Public profiles viewable" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users insert own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Attendance
CREATE POLICY "Users manage own attendance" ON attendance FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Admins read all attendance" ON attendance FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Areas
CREATE POLICY "Admins manage areas" ON areas FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Staff view assigned areas" ON areas FOR SELECT USING (assigned_staff_id = auth.uid());

-- Leads
CREATE POLICY "Leads access policy" ON leads FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') OR
  assigned_staff_id = auth.uid() OR
  (created_by_id = auth.uid() AND created_at > now() - interval '6 months')
);

-- Visit Reports
CREATE POLICY "Staff submit own reports" ON visit_reports FOR INSERT WITH CHECK (auth.uid() = staff_id);
CREATE POLICY "Staff view own reports" ON visit_reports FOR SELECT USING (auth.uid() = staff_id);
CREATE POLICY "Admins view all reports" ON visit_reports FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- GPS Logs
CREATE POLICY "Admins read all logs" ON gps_logs FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Users insert own logs" ON gps_logs FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Daily Work Plans
CREATE POLICY "Staff view own work plans" ON daily_work_plans FOR SELECT USING (auth.uid() = staff_id);
CREATE POLICY "Staff insert own work plans" ON daily_work_plans FOR INSERT WITH CHECK (auth.uid() = staff_id);
CREATE POLICY "Staff update own draft work plans" ON daily_work_plans FOR UPDATE USING (auth.uid() = staff_id);
CREATE POLICY "Admins view all work plans" ON daily_work_plans FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Admins update all work plans" ON daily_work_plans FOR UPDATE USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Expenses
CREATE POLICY "Staff view own expenses" ON expenses FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Staff insert expenses" ON expenses FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Staff update own expenses" ON expenses FOR UPDATE USING (auth.uid() = user_id AND is_auto_generated = false);
CREATE POLICY "Admins manage all expenses" ON expenses FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Audit Logs
CREATE POLICY "Audit logs read by admins" ON audit_logs FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Travel Summary
CREATE POLICY "Staff view own travel summary" ON daily_travel_summary FOR SELECT USING (auth.uid() = staff_id);
CREATE POLICY "Admins view all travel summaries" ON daily_travel_summary FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Admins update travel summary" ON daily_travel_summary FOR UPDATE USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- ============================================================
-- TRIGGERS & FUNCTIONS
-- ============================================================

-- A. Auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', 'employee');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- B. Update lead last_visit_date on report insert
CREATE OR REPLACE FUNCTION update_lead_last_visit()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE leads SET last_visit_date = NEW.timestamp WHERE id = NEW.lead_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_update_lead_visit ON visit_reports;
CREATE TRIGGER tr_update_lead_visit
  AFTER INSERT ON visit_reports
  FOR EACH ROW EXECUTE FUNCTION update_lead_last_visit();

-- C. Auto follow-up scheduling trigger
CREATE OR REPLACE FUNCTION public.auto_schedule_followup()
RETURNS TRIGGER AS $$
DECLARE
  v_lead_name    text;
  v_existing_plan uuid;
  v_existing_leads jsonb;
  v_new_lead_entry jsonb;
  v_max_seq      int;
BEGIN
  IF NEW.next_action_date IS NULL THEN RETURN NEW; END IF;
  IF NEW.outcome NOT IN ('follow-up', 'interested', 'Interested', 'follow_up') THEN RETURN NEW; END IF;

  SELECT name INTO v_lead_name FROM leads WHERE id = NEW.lead_id;
  SELECT id, planned_leads INTO v_existing_plan, v_existing_leads
  FROM daily_work_plans WHERE staff_id = NEW.staff_id AND date = NEW.next_action_date;

  IF v_existing_leads IS NOT NULL THEN
    SELECT COALESCE(MAX((elem->>'sequence')::int), 0) INTO v_max_seq
    FROM jsonb_array_elements(v_existing_leads) AS elem;
  ELSE
    v_max_seq := 0;
  END IF;

  IF v_existing_leads IS NOT NULL AND
     EXISTS (SELECT 1 FROM jsonb_array_elements(v_existing_leads) AS elem
             WHERE elem->>'lead_id' = NEW.lead_id::text) THEN
    RETURN NEW;
  END IF;

  v_new_lead_entry := jsonb_build_object(
    'lead_id',       NEW.lead_id,
    'lead_name',     COALESCE(v_lead_name, 'Unknown Party'),
    'sequence',      v_max_seq + 1,
    'is_followup',   true,
    'source_report', NEW.id,
    'note',          'Auto follow-up from visit on ' || NEW.timestamp::date::text
  );

  IF v_existing_plan IS NOT NULL THEN
    UPDATE daily_work_plans
    SET planned_leads = COALESCE(v_existing_leads, '[]'::jsonb) || jsonb_build_array(v_new_lead_entry)
    WHERE id = v_existing_plan;
  ELSE
    INSERT INTO daily_work_plans (staff_id, date, planned_leads, status)
    VALUES (NEW.staff_id, NEW.next_action_date, jsonb_build_array(v_new_lead_entry), 'draft')
    ON CONFLICT (staff_id, date) DO UPDATE
      SET planned_leads = COALESCE(daily_work_plans.planned_leads, '[]'::jsonb)
                          || jsonb_build_array(v_new_lead_entry);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS tr_auto_schedule_followup ON visit_reports;
CREATE TRIGGER tr_auto_schedule_followup
  AFTER INSERT ON visit_reports
  FOR EACH ROW EXECUTE FUNCTION public.auto_schedule_followup();

-- D. Work plan staff_id auto-fill
CREATE OR REPLACE FUNCTION public.handle_work_plan_staff_id()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.staff_id IS NULL THEN NEW.staff_id := auth.uid(); END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS tr_set_work_plan_staff_id ON daily_work_plans;
CREATE TRIGGER tr_set_work_plan_staff_id
  BEFORE INSERT ON public.daily_work_plans
  FOR EACH ROW EXECUTE FUNCTION public.handle_work_plan_staff_id();

-- ============================================================
-- GRANTS
-- ============================================================
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT ALL ON profiles TO authenticated;
GRANT ALL ON gps_logs TO authenticated;
GRANT ALL ON areas TO authenticated;
GRANT ALL ON leads TO authenticated;
GRANT ALL ON attendance TO authenticated;
GRANT ALL ON expenses TO authenticated;
GRANT ALL ON deviations TO authenticated;
GRANT ALL ON daily_work_plans TO authenticated;
GRANT ALL ON daily_travel_summary TO authenticated;
GRANT ALL ON visit_reports TO authenticated;
GRANT ALL ON audit_logs TO authenticated;

-- ============================================================
-- DONE! Schema setup complete.
-- ============================================================
